sonar.projectKey=shablenkoo_Refact_Project2
sonar.organization=shablenkoo
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=report.xml

sonar.maintainability.rating=A
sonar.reliability.rating=A
sonar.security.rating=A